def appName = "photo_viewage_app"
def appPath = appName + "/target"
def prop = "~/PhotoViewage.properties"


pipeline {
  agent any
  stages {
    stage("Clean Up") {
      steps {
        deleteDir()
      }
    }
    stage("Clone") {
      steps {
        sh "git clone -v git@github.com:GH94GitHub/photo_viewage_app.git"
      }
    }
    stage("Clean") {
      steps {
        dir("photo_viewage_app") {
        	sh "chmod u+x ./mvnw"
          sh "./mvnw clean"
        }
      }
    }
    stage("Install") {
      steps {
        dir("photo_viewage_app") {
          sh "./mvnw install -DskipTests"
        }
      }
    }
    stage("Move Config") {
      steps {
        dir("${appName}") {
         	sh "cp ${prop} ."
        }
      }
    }
    stage("Deploy") {
       steps {
         dir("${appPath}") {
         	sh "nohup java -jar PhotoViewage.jar -Dpropfile=application.properties &"
           echo "done"
         }
       }
     }
  }
}
