pipeline {
  agent any
  stages {
    stage("Clean Up") {
      steps {
        deleteDir()
      }
    }
    stage("Clone") {
      steps {
        sh "git clone -v git@github.com:GH94GitHub/photo_viewage_app.git"
      }
    }
    stage("Clean") {
      steps {
        dir("photo_viewage_app") {
          sh "mvn clean"
        }
      }
    }
    stage("Package") {
      steps {
        dir("photo_viewage_app") {
          sh "mvn install"
        }
      }
    }
    stage("Deploy") {
       steps {
         dir("photo_viewage_app/target") {
           echo "done"
         }
       }
     }
  }
}